#!/bin/bash

# Copyright (C) 2009-2015 Oliver Schulz <oliver.schulz@tu-dortmund.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.


PKG_NAME="Geant4"
PKG_TARNAME="geant4"

BASIC_BUILD_OPTS="
--fail-on-missing \
--enable-shared \
--enable-soversion \
"

ADDITIONAL_BUILD_OPTS="\
  -DGEANT4_USE_GDML=ON \
  -DGEANT4_USE_QT=ON \
  -DGEANT4_USE_OPENGL_X11=ON \
  -DGEANT4_USE_RAYTRACER_X11=ON \
  -DGEANT4_INSTALL_EXAMPLES=ON \
"

if (clhep-config --prefix &> /dev/null) ; then
	BASIC_BUILD_OPTS="${BASIC_BUILD_OPTS} -DGEANT4_USE_SYSTEM_CLHEP=ON -DCLHEP_ROOT_DIR=`clhep-config --prefix | sed 's/"//g'`"
else
	BASIC_BUILD_OPTS="${BASIC_BUILD_OPTS} -DGEANT4_USE_SYSTEM_CLHEP=OFF"
fi

DEFAULT_BUILD_OPTS=`echo ${BASIC_BUILD_OPTS} ${ADDITIONAL_BUILD_OPTS}`


WHAT="$1"

if [ -z "${WHAT}" ] ; then
	echo "Syntax: $0 WHAT [BUILD_OPTION] ..." 1>&2
	echo 1>&2
	echo "For \"WHAT\", specify either a version number (e.g. \"6.02.01\") to download, or" 1>&2
	echo "the path to the ${PKG_NAME} source directory (may be an rsync-compatible" 1>&2
	echo "remote path)." 1>&2

	exit 1
fi

shift 1


if ! . swmod.sh init ; then
	echo "ERROR: swmod not available, aborting." 1>&2
	exit 1
fi

BUILDDIR=`mktemp -t -d "$(whoami)-build-${PKG_TARNAME}-XXXXXX"`
echo "Build directory: \"${BUILDDIR}\""
CURRDIR=`pwd`

error_clean_abort() {
	echo "ERROR: Installation failed." 1>&2
	rm -rf "${BUILDDIR}"
	exit 1
}


error_noclean_abort() {
	echo "ERROR: Installation failed, build directory: \"${BUILDDIR}\"." 1>&2
	exit 1
}


if (echo "${WHAT}" | grep -q '^[0-9]\+[.][0-9]\+\([.][0-9]\+\)\?$') ; then
	PKG_VERSION="${WHAT}" \
	&& (
		cd "${BUILDDIR}" \
		PKG_VERSION=$(echo "${PKG_VERSION}" | sed 's/^\([0-9]\+\.[0-9]\+\)$/\1.00/') \
		&& PKG_VERSION_MAJOR=$(echo "${PKG_VERSION}" | cut -d '.' -f 1) \
		&& PKG_VERSION_MINOR=$(echo "${PKG_VERSION}" | cut -d '.' -f 2) \
		&& PKG_VERSION_MINOR=$(test "${PKG_VERSION_MAJOR}" -ge 10 && seq -f "%02g" "${PKG_VERSION_MINOR}" "${PKG_VERSION_MINOR}" || echo "${PKG_VERSION_MINOR}") \
		&& PKG_VERSION_PATCH=$(echo "${PKG_VERSION}" | cut -d '.' -f 3) \
		&& PKG_VERSION_PATCH=$(seq -f "%02g" "${PKG_VERSION_PATCH}" "${PKG_VERSION_PATCH}") \
		&& PKG_VERSION_DNL="${PKG_VERSION_MAJOR}.${PKG_VERSION_MINOR}" \
		&& PKG_VERSION_DNL=$(test "${PKG_VERSION_PATCH}" -ne 0 && echo "${PKG_VERSION_DNL}.p${PKG_VERSION_PATCH}" || echo "${PKG_VERSION_DNL}") \
		&& DOWNLOAD_URL="http://geant4.cern.ch/support/source/geant4.${PKG_VERSION_DNL}.tar.gz" \
		&& echo "Downloading ${PKG_NAME} version ${PKG_VERSION} from ${DOWNLOAD_URL}" \
		&& curl "${DOWNLOAD_URL}" |
			tar --strip-components 1 -C "${BUILDDIR}" --strip=1 -x -z \
	) || error_clean_abort
else
	PKG_FROM="${WHAT}" \
	&& echo "Copying ${PKG_NAME} sources from ${PKG_FROM} to ${BUILDDIR}" \
	&& rsync -rlpt "${PKG_FROM}/" "${BUILDDIR}/" \
	&& PKG_VERSION=`(cd "${BUILDDIR}/" && (cat CMakeLists.txt | grep 'set.*PROJECT_NAME.*_VERSION[^_]' | grep -o '[0-9.]\+'))` \
	|| error_clean_abort
fi \
&& . swmod.sh setinst "${PKG_TARNAME}@${PKG_VERSION}" \
|| error_clean_abort

echo "Installing ${PKG_NAME} version ${PKG_VERSION}"
echo "Install prefix: ${SWMOD_INST_PREFIX}"
echo "Build options:" ${DEFAULT_BUILD_OPTS} "$@"

NTHREADS=`grep -c '^processor' /proc/cpuinfo 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 4`
echo "Building with ${NTHREADS} parallel threads."

(
	cd "${BUILDDIR}" \
	&& mkdir build && cd build \
	&& cmake -DCMAKE_INSTALL_PREFIX="${SWMOD_INST_PREFIX}" ${DEFAULT_BUILD_OPTS} "$@" "`pwd`/.." \
    && make -j"${NTHREADS}" install \
	&& echo '. "$SWMOD_PREFIX/bin/geant4.sh" > /dev/null' > "${SWMOD_INST_PREFIX}/swmodrc.sh" \
	&& ( (echo "${SWMOD_LOADED_PREFIXES}" | grep -q '/clhep/') && (. swmod.sh adddeps clhep@"`clhep-config --version | grep -o '[0-9.]*'`") )
) || error_noclean_abort

echo ""
echo "Successfully installed ${PKG_NAME} to \"${SWMOD_INST_PREFIX}\"."
echo "Use"
echo ""
echo "    swmod load ${PKG_TARNAME}@${PKG_VERSION}"
echo ""
echo "to load the newly installed ${PKG_NAME}."

rm -rf "${BUILDDIR}"
